<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Postmark\\' => array($vendorDir . '/wildbit/postmark-php/src'),
    'Parsedown' => array($vendorDir . '/erusev/parsedown'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'Lob\\Tests' => array($vendorDir . '/lob/lob-php/tests'),
    'Lob' => array($vendorDir . '/lob/lob-php/src'),
    'Laracasts\\Flash' => array($vendorDir . '/laracasts/flash/src'),
    'HTMLPurifier' => array($vendorDir . '/ezyang/htmlpurifier/library'),
    'Cornford\\Googlmapper' => array($vendorDir . '/cornford/googlmapper/src'),
);
